server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ { proxy_pass http://backend:18000/api/; proxy_buffering off; }
  location /media/ { proxy_pass http://backend:18000/media/; }
  location / { try_files $uri /index.html; }
}
